// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'only Android and Web are supported.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_VT4w-T9X3ogoOBRfWC1tuSF2Daz1PE',
    appId: '1:340961311064:web:09e0c544ff302d775f4d2d',
    messagingSenderId: '340961311064',
    projectId: 'kinniya-2025-6a74f',
    authDomain: 'kinniya-2025-6a74f.firebaseapp.com',
    storageBucket: 'kinniya-2025-6a74f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CABceDEALA97uXmOkPxpEDkS-royRIc',
    appId: '1:340961311064:android:46e46d391a68c6205f4d2d',
    messagingSenderId: '340961311064',
    projectId: 'kinniya-2025-6a74f',
    storageBucket: 'kinniya-2025-6a74f.firebasestorage.app',
  );
}
